routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{language}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang'
]);

Route::group(['middleware' => 'language'], function () {
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
    Route::get('/register-form', ['as' => 'form.register','uses' => 'FormController@index']);
    Route::get('/register-form-for-favorites', ['as' => 'form.register','uses' => 'FormController@favorites']);
    Route::post('/professionals-form-store', ['as' => 'professionals.form.store','uses' => 'FormController@storeProfessionals']);
    Route::post('/activists-form-store', ['as' => 'activists.form.store','uses' => 'FormController@storeActivists']);
    
    Auth::routes();
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth']], function() {
    App::setlocale('ru');
    Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::post('/update', ['as' => 'dashboard.update-settings', 'uses' => 'DashboardController@update']);
    Route::get('/contacts', ['as' => 'contacts.index', 'uses' => 'ContactsController@index']);
    Route::post('/contacts', ['as' => 'contacts.update', 'uses' => 'ContactsController@update']);
    Route::resource('news', 'NewsController', ['except' => 'show']);
    Route::resource('participate-notes', 'ParticipateNoteController', ['except' => 'show']);
    Route::resource('partners', 'PartnerController', ['except' => 'show']);
    Route::resource('mentors', 'MentorController', ['except' => 'show']);
    Route::resource('days', 'DayController', ['except' => 'show']);
    Route::resource('lectures', 'LectureController', ['except' => 'show']);
    Route::resource('rules', 'RuleController', ['except' => 'show']);
    Route::resource('menu', 'MenuController', ['except' => 'show']);
    Route::resource('albums', 'AlbumController', ['except' => 'show']);
    Route::resource('album-items', 'AlbumItemController', ['except' => 'show']);
    Route::post('upload-images', ['as' => 'album-items.upload-images', 'uses' => 'AlbumItemController@uploadImages']);

    Route::post('/menu/positions-update', ['as' => 'menu.positions-update', 'uses' => 'MenuController@positionsUpdate']);
});

app/ParticipateNote.php
<?php

namespace App;

use \Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class ParticipateNote extends Model
{
	use Translatable;

	public $translatedAttributes = ['title', 'content'];
}

app/Http/Controllers/Dashboard/AlbumController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Album;
use App\AlbumItem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AlbumController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::all();

        return view('dashboard.albums.index', compact('albums'));
    }

    public function create()
    {
        $album_items = AlbumItem::all();
        // dd($album_items->count());
        if (!$album_items->count()) {
            return redirect(route('album-items.index'))
                ->with('error_message', 'Вам нужно сначала добавить элементы для создания альбома');
        }

        return view('dashboard.albums.create', compact('album_items'));
    }

    public function store(Request $request)
    {
        if (!$request->album_items) {
            return redirect()->back()
                ->with('error_message', 'Вы не можете создавать пустые альбомы');
        }

        $this->validate($request, [
            'name_ru' => 'required',
            'name_en' => 'required',
            'cover_image_path' => 'required',
        ]);

        $album = new Album;
        $album->cover_image_path = $request->cover_image_path;

        $album->translateOrNew('en')->name   = $request->name_en;
        $album->translateOrNew('ru')->name   = $request->name_ru;

        $album->save();

        $album->albumItems()->sync($request->album_items, false);

        return redirect()->route('albums.index')
            ->with('flash_message',
                'Альбом ' . $album->name . ' добавлен!');
    }

    public function edit($id)
    {
        $album_items = AlbumItem::all();

        $album = Album::find($id);

        return view('dashboard.albums.edit', compact('album', 'album_items'));
    }

    public function update(Request $request, $id)
    {
        if (!$request->album_items) {
            return redirect()->back()
                ->with('error_message', 'Вы не можете создавать пустые альбомы');
        }

        $this->validate($request, [
            'name_ru' => 'required',
            'name_en' => 'required',
            'cover_image_path' => 'required',
        ]);

        $album = Album::findOrFail($id);
        $album->cover_image_path = $request->cover_image_path;
        
        $album->translate('en')->name   = $request->name_en;
        $album->translate('ru')->name   = $request->name_ru;

        $album->update();

        $album->albumItems()->sync($request->album_items);

        return redirect(route('albums.index'))
            ->with('flash_message',
                'Альбом ' . $album->name . ' обновлен!');
    }

    public function destroy(Request $request, $id)
    {
        $album = Album::findOrFail($id);

        if($request->has('confirmed') && $request->get('confirmed')) {
            $album->delete();

            return redirect(route('albums.index'))
                ->with('error_message', 
                    'Альбом ' . $album->name . ' удален');
        } else {
            return view('dashboard.albums.confirm-delete', compact('album'));
        }
    }
}

app/Http/Controllers/Dashboard/AlbumItemController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Image;
use App\AlbumItem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class AlbumItemController extends Controller
{
    public function index()
    {
        $album_items = AlbumItem::all();

        return view('dashboard.album-items.index', compact('album_items'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'url' => 'max:191',
        ]);

        $album_item = new AlbumItem;

        $album_item->type = 'url';
        $album_item->url = $request->url;

        $album_item->save();

        return redirect(route('album-items.index'))
            ->with('flash_message', 'Элемент успешно добавлен!');
    }

    public function uploadImages(Request $request)
    {
    	$this->validate($request, [
    		'image' => 'image|max:2000',
    	]);

    	if ($request->hasFile('image') && $request->file('image')->isValid()) {
            $image = $request->file('image');
            $location = public_path('storage/gallery/');
            $extension = "." . $image->getClientOriginalExtension();
            $image_name = time();
            $original_image_name = $image_name . $extension;
            Storage::putFileAs('public/gallery', $image, $original_image_name); //saving original image
            $original_image_path = 'storage/gallery' . $original_image_name;

            $resolutions = ['large' => '1024', /*'medium' => '512',*/ 'small' => '128'];

            //creating resized images

            foreach ($resolutions as $size => $resolution) {
                Image::make($image)->resize($resolution, null, function ($constraint) {
                    $constraint->aspectRatio();
                })->save($location . '/' . $image_name . '-' . $resolution . $extension);

                ${$size . "_image_path"} = '/storage/gallery/' . $image_name . '-' . $resolution . $extension;
            }

        } else {
            return redirect('403');
        }
        
        $album_item = new AlbumItem;
        $album_item->type = 'image';
        $album_item->original_image = $original_image_path;
        $album_item->large_image = $large_image_path;
        // $album_item->medium_image = $medium_image_path;
        $album_item->small_image = $small_image_path;
        
        $album_item->save();

        return redirect(route('album-items.index'))
            ->with('flash_message', 'Элемент успешно добавлен!');
    }

    public function destroy(Request $request, $id)
    {
        $album_item = AlbumItem::find($id);

        if($request->has('confirmed') && $request->get('confirmed')) {
            $album_item->delete();

            return redirect(route('album-items.index'))
                ->with('error_message', 
                    'Элмент  удален');
        } else {
            return view('dashboard.album-items.confirm-delete', compact('album_item'));
        }
    }
}

app/Http/Controllers/Dashboard/ContactsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Contacts;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactsController extends Controller
{
	public function index()
    {
        $contacts_model = Contacts::find(1) ? Contacts::find(1) : new Contacts;

        return view('dashboard.contacts.index', compact('contacts_model'));
    }

    public function update(Request $request)
    {
    	// dd($request->contacts);
        $contacts_model = Contacts::find(1);
        $contacts_model->contacts = $request->contacts;

        $contacts_model->translateOrNew('ru')->translated_contacts = $request->translated_contacts_ru;
        // dd($request->translated_contacts_ru);
        $contacts_model->translateOrNew('en')->translated_contacts = $request->translated_contacts_en;

        $contacts_model->update();

        return redirect(route('contacts.index'))
            ->with('flash_message',
                'Контакты обновлены!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Settings;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings_model = Settings::find(1);

        return view('dashboard.index', compact('settings_model'));
    }

    public function update(Request $request)
    {
        $settings = Settings::find(1);
        
        $settings->settings = $request->settings;

        $settings->translateOrNew('ru')->translated_settings = $request->translated_settings_ru;
        $settings->translateOrNew('en')->translated_settings = $request->translated_settings_en;

        $settings->update();

        return redirect(route('dashboard'))
            ->with('flash_message',
                'Настройки обновлены!');
    }
}

app/Http/Controllers/Dashboard/DayController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Day;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DayController extends Controller
{
    public function index()
    {
        $days = Day::all();

        return view('dashboard.days.index', compact('days'));
    }

    public function create()
    {
        return view('dashboard.days.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'date' => 'required|unique:days'
        ]);

        $day = Day::create(
        	$request->only('date')
        );

        return redirect()->route('days.index')
            ->with('flash_message',
                'День ' . $day->date . ' добавлен!');
    }

    public function edit($id)
    {
        $day = Day::find($id);

        return view('dashboard.days.edit', compact('day'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'date' => 'required|unique:days,date,' . $id,
        ]);

        $day = Day::findOrFail($id);

        $day->update(
        	$request->only('date')
        );

        return redirect(route('days.index'))
            ->with('flash_message',
                'День ' . $day->date . ' обновлен!');
    }

    public function destroy(Request $request, $id)
    {
        $day = Day::findOrFail($id);

        if($request->has('confirmed') && $request->get('confirmed')) {
            $day->delete();

            return redirect(route('days.index'))
                ->with('error_message', 
                    'Новость ' . $day->title . ' удалена');
        } else {
            return view('dashboard.days.confirm-delete', compact('day'));
        }
    }
}

app/Http/Controllers/Dashboard/LectureController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Day;
use App\Mentor;
use App\Lecture;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LectureController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lectures = Lecture::all();

        return view('dashboard.lectures.index', compact('lectures'));
    }

    public function create()
    {
        $mentors = Mentor::all();
        $days = Day::all()->pluck('date', 'id')->prepend('--', 0);

        return view('dashboard.lectures.create', compact('mentors', 'days'));
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'start_at' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required',

        ]);

        $lecture = new Lecture;

        $lecture->start_at = $request->start_at;
        $lecture->end_at   = $request->end_at;
        $lecture->day_id   = $request->day_id == 0 ? null : $request->day_id;

        $lecture->translateOrNew('en')->title   = $request->title_en;
        $lecture->translateOrNew('en')->place   = $request->place_en;
        $lecture->translateOrNew('en')->content = $request->content_en;

        $lecture->translateOrNew('ru')->title   = $request->title_ru;
        $lecture->translateOrNew('ru')->place   = $request->place_ru;
        $lecture->translateOrNew('ru')->content = $request->content_ru;

        $lecture->save();

        $lecture->mentors()->sync($request->mentors, false);

        return redirect()->route('lectures.index')
            ->with('flash_message',
                'Лекция ' . $lecture->title . ' добавлена!');
    }

    public function edit($id)
    {
        $mentors = Mentor::all();
        $days = Day::all()->pluck('date', 'id')->prepend('--', 0);
        $lecture = Lecture::find($id);


        return view('dashboard.lectures.edit', compact('lecture', 'mentors', 'days'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'start_at' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required',
        ]);

        $lecture = Lecture::findOrFail($id);

        $lecture->start_at = $request->start_at;
        $lecture->end_at   = $request->end_at;

        $lecture->day_id   = $request->day_id == 0 ? null : $request->day_id;

        $lecture->translateOrNew('en')->title   = $request->title_en;
        $lecture->translateOrNew('en')->place   = $request->place_en;
        $lecture->translateOrNew('en')->content = $request->content_en;

        $lecture->translateOrNew('ru')->title   = $request->title_ru;
        $lecture->translateOrNew('ru')->place   = $request->place_ru;
        $lecture->translateOrNew('ru')->content = $request->content_ru;

        $lecture->update();

        $lecture->mentors()->sync($request->mentors);

        return redirect(route('lectures.index'))
            ->with('flash_message',
                'Лекция ' . $lecture->title . ' обновлена!');
    }

    public function destroy(Request $request, $id)
    {
        $lecture = Lecture::findOrFail($id);

        if($request->has('confirmed') && $request->get('confirmed')) {
            $lecture->delete();

            return redirect(route('lectures.index'))
                ->with('error_message', 
                    'Новость ' . $lecture->title . ' удалена');
        } else {
            return view('dashboard.lectures.confirm-delete', compact('lecture'));
        }
    }
}

resources/views/dashboard/participate-notes/confirm-delete.blade.php
@extends('layouts.admin-without-sidebar')

@section('content')
        <div class="card w-50 m-auto mt-5">
            <div class="card-body">
                <h3 class="card-title">Confirm delete</h3>
                <p class="card-text">
                    После того как вы нажмете "Удалить" запись "{{ $participate_note->name_ru }}" будет удалена,
                    и вы не сможете восстановить её в будущем.
                </p>
                {{ Form::open(['route' => ['participate-notes.destroy', $participate_note], 'method' => 'delete', 'style' => 'display: inline-block']) }}
                    {{ Form::hidden('confirmed', true) }}
                    <button class="btn btn-danger">Удалить</button>
                {{ Form::close() }}
                <a class="btn btn-secondary" href="{{ route('participate-notes.index') }}">Отмена</a>
            </div>
        </div>
@endsection

resources/views/dashboard/participate-notes/create.blade.php
@extends('layouts.admin')

@section('title')
    Добавить запись
@endsection

@section('header')
    Добавить запись
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

{{ Form::open(['route' => 'participate-notes.index']) }}

    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Русский язык</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#profile" role="tab">Английский язык</a>
        </li>
        {{-- <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#contact" role="tab">Мета-даные</a>
        </li> --}}
    </ul>

    <div class="tab-content pt-3">
        <!-- Русская версия -->
        <div class="tab-pane fade show active" id="home" role="tabpanel">
            <div class="form-group">
                {{ Form::label('title_ru', 'Заголовок рус.') }}
                {{ Form::text('title_ru', null, ['class' => 'form-control' . ($errors->has('title_ru') ? ' is-invalid' : '')]) }}
        
                @if($errors->has('title_ru'))
                    @foreach ($errors->get('title_ru') as $message)
                        <div class="invalid-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>

            <div class="form-group">
                {{ Form::label('content_ru', 'Текст.рус') }}
                {{ Form::textarea('content_ru', null, ['class' => 'form-control tinymce-val' . ($errors->has('content_ru') ? ' is-invalid' : '')]) }}

                @if($errors->has('content_ru'))
                    @foreach ($errors->get('content_ru') as $message)
                        <div class="form-control-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>
        </div>
        <!-- Конец русской версии -->

        <!-- Английская версия -->
        <div class="tab-pane fade" id="profile" role="tabpanel">
            <div class="form-group">
                {{ Form::label('title_en', 'Заголовок анг.') }}
                {{ Form::text('title_en', null, ['class' => 'form-control' . ($errors->has('title_en') ? ' is-invalid' : '')]) }}

                @if($errors->has('title_en'))
                    @foreach ($errors->get('title_en') as $message)
                        <div class="invalid-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>

            <div class="form-group">
                {{ Form::label('content_en', 'Текст.анг') }}
                {{ Form::textarea('content_en', null, ['class' => 'form-control tinymce-val' . ($errors->has('content_en') ? ' is-invalid' : '')]) }}

                @if($errors->has('content_en'))
                    @foreach ($errors->get('content_en') as $message)
                        <div class="form-control-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>
        </div>
        <!-- Конец английской версии -->

        <!-- Мета-данные -->
        {{-- <div class="tab-pane fade" id="contact" role="tabpanel">
            
        </div> --}}
        <!-- Конец мета-данных -->
    </div>

    {{ Form::submit('Добавить', ['class' => 'btn btn-outline-primary']) }}

{{ Form::close() }}

@endsection

resources/views/dashboard/participate-notes/edit.blade.php
@extends('layouts.admin')

@section('title')
    Редактирование новости {{ $participate_note->name_ru }}
@endsection

@section('header')
    Редактирование новости {{ $participate_note->name_ru }}
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


{{ Form::model($participate_note, ['route' => ['participate-notes.update', $participate_note->id], 'method' => 'PUT']) }}

    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Русский язык</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#profile" role="tab">Английский язык</a>
        </li>
        {{-- <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#contact" role="tab">Мета-даные</a>
        </li> --}}
    </ul>

    <div class="tab-content pt-3">
        <!-- Русская версия -->
        <div class="tab-pane fade show active" id="home" role="tabpanel">
            <div class="form-group">
                {{ Form::label('title_ru', 'Заголовок рус.') }}
                {{ Form::text('title_ru', $participate_note->translate('ru')->title, ['class' => 'form-control' . ($errors->has('title_ru') ? ' is-invalid' : '')]) }}
        
                @if($errors->has('title_ru'))
                    @foreach ($errors->get('title_ru') as $message)
                        <div class="invalid-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>

            <div class="form-group">
                {{ Form::label('content_ru', 'Текст.рус') }}
                {{ Form::textarea('content_ru', $participate_note->translate('ru')->content, ['class' => 'form-control tinymce-val' . ($errors->has('content_ru') ? ' is-invalid' : '')]) }}

                @if($errors->has('content_ru'))
                    @foreach ($errors->get('content_ru') as $message)
                        <div class="form-control-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>
        </div>
        <!-- Конец русской версии -->

        <!-- Английская версия -->
        <div class="tab-pane fade" id="profile" role="tabpanel">
            <div class="form-group">
                {{ Form::label('title_en', 'Заголовок анг.') }}
                {{ Form::text('title_en', $participate_note->translate('en')->title, ['class' => 'form-control' . ($errors->has('title_en') ? ' is-invalid' : '')]) }}

                @if($errors->has('title_en'))
                    @foreach ($errors->get('title_en') as $message)
                        <div class="invalid-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>

            <div class="form-group">
                {{ Form::label('content_en', 'Текст.анг') }}
                {{ Form::textarea('content_en', $participate_note->translate('en')->content, ['class' => 'form-control tinymce-val' . ($errors->has('content_en') ? ' is-invalid' : '')]) }}

                @if($errors->has('content_en'))
                    @foreach ($errors->get('content_en') as $message)
                        <div class="form-control-feedback">{{ $message }}</div>
                    @endforeach
                @endif
            </div>
        </div>

        {{ Form::submit('Обновить', ['class' => 'btn btn-outline-primary']) }}

{{ Form::close() }}


@endsection

resources/views/dashboard/participate-notes/index.blade.php
@extends('layouts.admin')

@section('title')
    Что ты получишь?
@endsection

@section('header')
    Что ты получишь?
@endsection

@section('content')
<div class="col-lg-3">
    <div class="form-group create-button">
        <a href="{{ route('participate-notes.create') }}" class="btn btn-outline-primary">Создать запись</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Заголовок</th>
            {{-- <th>Текст</th> --}}
            <th>Операция</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($participate_notes as $participate_note)
                <tr>
                    <td>{{ $participate_note->title }}</td>
                    {{-- <td>{{ str_limit($participate_note->content_ru, 120) }}</td> --}}
                    <td>
                        {{ Form::open(['route' => ['participate-notes.destroy', $participate_note], 'method' => 'delete']) }}
                            <div class="btn-group btn-group-sm" role="group">
                                <a href="{{ route('participate-notes.edit', $participate_note) }}" class="btn btn-light">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>

                                <button class="btn btn-danger">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </div>
                        {{ Form::close() }}
                    </td>
                </tr>
        @endforeach
    </tbody>
</table>
@endsection